In [3]:
import gymnasium as gym
import rlenvs

# env = gym.make("CartPole-v1")
env = gym.make("custom/DiscreteCartPole-v1")

observation, info = env.reset(seed=82, options={"sizes":(1, 20, 20, 20)})
observation

/home/gui/Área de Trabalho/rlenvs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:167: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.deprecation(
/home/gui/Área de Trabalho/rlenvs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:180: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.deprecation(


array([ 0.     ,  0.19512, -0.01756,  0.29268], dtype=float32)

In [4]:
import numpy as np
from rlenvs import DiscreteCartPole

obj = DiscreteCartPole()

_, values = obj.discretize(observation)
print(obj.enumerate_state(observation))
print(np.array(values, dtype=np.float32))


1480
[ 0.       0.39024 -0.00585  0.58537]


In [41]:
observation,reward, terminated, truncated, info = env.step(1)

_, values = obj.discretize(observation)
print(observation, terminated)
print(obj.enumerate_state(observation))
print(np.array(values, dtype=np.float32))

[ 0.          1.5        -0.         -0.16666667] False
2216
[ 0.          1.5         0.00428571 -0.16666667]


In [339]:
obj.factor_spaces

[array([], dtype=float64),
 array([-1.5       , -1.10204082, -0.76530612, -0.48979592, -0.2755102 ,
        -0.12244898, -0.03061224, -0.        ,  0.03061224,  0.12244898,
         0.2755102 ,  0.48979592,  0.76530612,  1.10204082,  1.5       ]),
 array([-0.21      , -0.15428571, -0.10714286, -0.06857143, -0.03857143,
        -0.01714286, -0.00428571, -0.        ,  0.00428571,  0.01714286,
         0.03857143,  0.06857143,  0.10714286,  0.15428571,  0.21      ]),
 array([-1.5       , -0.66666667, -0.16666667, -0.        ,  0.16666667,
         0.66666667,  1.5       ])]

In [5]:
np.concatenate([-np.linspace(0, 1.8**.5, (9//2))[::-1]**2, np.linspace(0, 1.8**.5, (9//2))[1:]**2])

array([-1.8, -0.8, -0.2, -0. ,  0.2,  0.8,  1.8])

In [1]:
import gymnasium as gym
import rlenvs

n=500

# env = gym.make("custom/DiscreteCartPole-v1", render_mode="human")
# env = gym.make("custom/DiscreteCartPole-v1")
env = gym.make("custom/CartPole-v1")
# env = gym.make("CartPole-v1")

# observation, info = env.reset(seed=82)
observation, info = env.reset(seed=82, options={"masspole":.45, "length":1.0})
observation

array([ 0.04976388,  0.03547879, -0.02823136,  0.04801454], dtype=float32)

In [4]:
env.state

/home/gui/Área de Trabalho/rlenvs/.venv/lib/python3.9/site-packages/gymnasium/core.py:311: UserWarning: WARN: env.state to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.state` for environment variables or `env.get_wrapper_attr('state')` that will search the reminding wrappers.
  logger.warn(


array([ 0.        ,  0.07777778, -0.02333333,  1.2       ], dtype=float32)

In [5]:
env.enumerated_state

/home/gui/Área de Trabalho/rlenvs/.venv/lib/python3.9/site-packages/gymnasium/core.py:311: UserWarning: WARN: env.enumerated_state to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.enumerated_state` for environment variables or `env.get_wrapper_attr('enumerated_state')` that will search the reminding wrappers.
  logger.warn(


1090